spring:
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    enabled: false
    contexts: test
    drop-first: true
    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:task-manager}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:example}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest

